name = "auto-vault-api"
main = "src/index.ts"
compatibility_date = "2023-01-01"

# Add your account ID
# account_id = ""

# Environment variables will be populated during deployment
[vars]
BUNGIE_API_KEY = ""
BUNGIE_CLIENT_ID = ""
BUNGIE_CLIENT_SECRET = ""

# KV Namespace for storing user data
[[kv_namespaces]]
binding = "AUTO_VAULT_USERS"
id = "xxxxxxxx"  # Replace with actual KV namespace ID during deployment

# Schedule the worker to run every 15 seconds
[triggers]
crons = ["*/15 * * * * *"]  # Every 15 seconds